# # config.yaml
# # "k8s1" "helm-evn-test1" "bpr-account-getaccountinfo"
# app_names=("k8s1" "helm-evn-test1" "bpr-account-getaccountinfo "hello1" "hello2" "hello5" "hello3" "hello4" "hello6")

# repo="https://github.com/karisa537/HelmChartsRepos.git"
# path="applications"
# dest_name_space="helm-deployments"
# project_name="test-project"
# values_file="values.yaml"
# branch_name="test"

  # "hello3"
  # "hello4"
  # "hello6"
  # "k8s1"
  # "helm-evn-test1"
  # "bpr-account-getaccountinfo"


app_names=(

  "hello1"
  "hello2"
  "hello5"
)
repo="https://github.com/karisa537/HelmChartsRepos.git"
path="applications"
dest_name_space="helm-deployments"
project_name="test-project"
values_file="values.yaml"
branch_name="test"