apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-deployment
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      server: {{ .Values.name }}
  template:
    metadata:
      labels:
        server: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.image.name }}:{{ .Values.image.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.image.port }}
          env:
          - name: DB_USERNAME  # Setting Database username from Secret
            valueFrom:
              secretKeyRef:
                key: db.username
                name: {{ .Chart.Name }}-secret
          - name: DB_PASSWORD # Setting Database password from Secret
            valueFrom:
              secretKeyRef:
                key: db.password
                name: {{ .Chart.Name }}-secret     
          - name: "USERNAME"
            valueFrom:
              secretKeyRef:
                key:  username
                name: {{ .Chart.Name }}-secret
          - name: "PASSWORD"
            valueFrom:
              secretKeyRef:
                key:  password
                name: {{ .Chart.Name }}-secret
          envFrom:
          - configMapRef:
              name: {{ .Chart.Name }}-configmap        
          - secretRef:
              name: {{ .Chart.Name }}-secret