{{- if .Values.createConfigMap -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: ftl-{{ .Chart.Name }}-generic
data:
{{- range $key, $value := .Values.genericconfigs }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}